### PR TITLE
Consolidate CorrelationScores and Reports tables

### PR DESCRIPTION
**Pull request by wilsonianb**
Drops CorrelationScores and ValidationReports tables

Replaces previous /reports endpoints with the following:
* /reports/:date
* /validators/:validation_public_key/reports

Report entries include the following for each validator:
* validations - total number of validations
* agreement_validations - number of validations in agreement with cluster
* disagreement_validations - number of validations not in agreement with cluster
* agreement_coefficient
* disagreement_coefficient

### CODE REVIEW

**Comment by wilsonianb** [comment]
:+1: unless this should include grunt task to backfill reports

**Comment by wilsonianb** [comment]
Should I not be committing changes to api_doc assets?

**Comment by stevenzeiler** [comment]
I kind of like having the actual apidoc assets commited, what do you think?

**Comment by wilsonianb** [comment]
It might result in more conflicts, since it's updated every time the api starts.

**Comment by stevenzeiler** [comment]
The change to database tables breaks the `npm run db:seed` command

**Comment by wilsonianb** [comment]
Hmm, I set `agreement_coefficient` to null if there are no cluster validations (can't divide by 0). So even though we should always have cluster validations, I should allow `agreement_coefficient` to be null?

**Comment by stevenzeiler** [comment]
I dropped my development database and re-ran the migrations, then `npm run db:seed` without any errors.

**Comment by wilsonianb** [comment]
That's because you removed the report creation.

**Comment by stevenzeiler** [comment]
Haha yes but I re-added it and performed that same test, and also forced push back to github.

**Comment by stevenzeiler** [comment]
Will the webapp client need to generate the date string `08-12-2015` now in order to construct the URL for the right report?

For example `https://api.validators.ripple.com/reports/08-12-2015` instead of `https://api.validators.ripple.com/reports`?

If so I'm fine with merging to staging before the webapp updates but let's keep it out of production until we can push the corresponding webapp change.

**Comment by wilsonianb** [comment]
Correct, I added https://ripplelabs.atlassian.net/browse/DEC-523

**Comment by stevenzeiler** [comment]
Thanks.

**Comment by stevenzeiler** [comment]
:+1:

**Comment by wilsonianb** [comment]
ReportService now throws an error if there are no cluster validations.
Removed changes to api-doc.

**Comment by stevenzeiler** [comment]
After running `npm run db:seed` there is one report in my database, but it does not show up when I query GET /reports/08-12-2015.
````
{
    "report": null
}
````

**Comment by wilsonianb** [comment]
date should be `YYYY-MM-DD`

**Comment by stevenzeiler** [comment]
I would be more comfortable merging this if we had a grunt task to backfill the data. Right now it is difficult to develop the front end webapp without a good amount of data from the API.

**Comment by wilsonianb** [comment]
Report history is now back filled at startup

**Comment by stevenzeiler** [comment]
There aren't any report_entries created by `npm run db:seed`, are there supposed to be?

**Comment by stevenzeiler** [comment]
LGTM :+1:

**Comment by wilsonianb** [comment]
Let's drop these tables!

**Pull request merged**
